[tool.poetry]
name = "backend"
version = "0.1.0"
description = ""
authors = ["mohamedkhedr <mohamed.khedr@bld.ai>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
django = "^4.1.6"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
